using System;

namespace MobaProtocol
{
	public enum LobbyCode : byte
	{
		C2L_JoinQueue = 11,
		G2L_JoinQueue = 11,
		L2C_JoinQueue = 11,
		L2S_JoinQueue = 11,
		S2L_JoinQueue = 11,
		C2L_OutQueue,
		L2C_OutQueue = 12,
		L2C_StartGame,
		C2L_QueryPvpState,
		L2C_QueryPvpState = 14,
		RefreshPlayerPvpState,
		C2L_ForceQuitPvp,
		L2C_ForceQuitPvp = 16,
		L2C_LobbyShutdown,
		C2L_OnUserQuit,
		L2S_PlayerOutline,
		L2S_Playerconnect,
		LobbyStart = 50,
		C2L_LoginLobby,
		C2L_FakeLoginLobby,
		L2C_LoginLobby,
		JoinQueueTeam,
		S2L_JoinQueueTeam = 54,
		L2S_JoinQueueTeam = 54,
		L2C_ServerNotify,
		C2L_Newbie,
		L2C_Newbie = 56,
		C2L_OutReady,
		L2C_OutReady = 57,
		L2S_RoomBack,
		S2C_RoomBack = 58,
		L2S_RoomEnd,
		C2L_ReadySelectHero,
		L2C_ReadySelectHero = 60,
		L2C_RoomReady,
		C2L_ReadyCheckOK,
		L2C_ReadyCheckOK = 62,
		L2C_ReadyCheckAllOK,
		C2L_SelectSelfDefSkill,
		L2C_SelectSelfDefSkill = 64,
		C2L_SelectHeroSkin,
		L2C_SelectHeroSkin = 65,
		L2C_WaitForSkin,
		C2L_RoomSelectHero,
		L2C_RoomSelectHero = 67,
		C2L_RoomSelectHeroOK,
		L2C_RoomSelectHeroOK = 68,
		C2L_CaptionLobby,
		L2C_CaptionLobby = 69,
		C2L_RoomSelectRandomHero,
		L2C_RoomSelectRandomHero = 70,
		G2L_RoomSelectRandomHeroId,
		L2G_RoomSelectRandomHeroId = 71,
		C2L_RoomReqChangeHero,
		L2C_RoomReqChangeHero = 72,
		C2L_RoomRespChangeHero,
		L2C_RoomRespChangeHero = 73,
		C2L_RoomRandomHero,
		L2C_RoomRandomHero = 74,
		L2C_CanExchangeHeroList,
		L2C_ModifyState,
		C2L_RoomCancelReqChangeHero,
		L2C_RoomCancelReqChangeHero = 77,
		C2L_UserBack,
		L2C_UserBack = 78,
		C2L_LookFriendFight,
		L2C_LookFriendFight = 79,
		L2C_TipMessage,
		C2L_GM_CMD,
		L2S_NoticePlayerPvpState,
		L2Se_LobbyShutDown,
		L2C_BattleNotification
	}
}
