using System;

namespace MobaProtocol
{
	public enum MobaEventKey : byte
	{
		UserId = 1,
		UserData,
		Message,
		Sit,
		Bystander,
		PlayerInfo,
		Amounts,
		TypeRound,
		NoSeatDealer,
		NoSeatSmallBlind,
		NoSeatBigBlind,
		TotalPortAmnt,
		Action,
		AmountPlayed,
		NoSeat,
		MoneyPotId,
		AmountWon,
		MoneySafeAmnt,
		LastNoSeat,
		GameCardIds,
		IsPlaying,
		MoneyBetAmnt,
		TotalRounds,
		StepID,
		NickName,
		Chip,
		MessageContent,
		Level,
		LevelExp,
		SendNoSeat,
		ReceiverNoSeat,
		GiftId,
		PlayingNoSeats,
		AchievementNumber,
		RoomType,
		RoomID,
		GameServerAddress,
		TaxAmnt,
		WinnerSeats,
		AttachedPlayerSeats,
		IsKick,
		HigherBet,
		PlayerLeaveType,
		StatusTipsMsgType,
		StatusTipsMsgParams,
		BigBlind,
		PlayRankList,
		ActorNr = 254,
		TargetActorNr = 253,
		ActorList = 252,
		Properties = 251,
		ActorProperties = 249,
		GameProperties = 248,
		Data = 245,
		CustomContent = 245
	}
}
