using System;

namespace MobaProtocol
{
	public enum MobaErrorCode
	{
		Md5Error = -1,
		Ok,
		SelectGameServerError = 5,
		MoneyShortage = 10,
		BattleUnlockError,
		ReqMemberExisting,
		ShopTimeout,
		EnergyShortage,
		HeroNotExist,
		PhoneGetCodeError = 20,
		PhoneCodeError,
		FindAccountPasswdError,
		UserNotInArea = 30,
		InvalidOperation = 198,
		InvalidParameter,
		CustomError,
		Sucess,
		NotInRedPacketTime = 300,
		RedPacketHaveNothing,
		LargeTimeDiff,
		DontHaveRedPacket,
		SystemError = 500,
		NoResult = 505,
		DataError,
		GuaJiPunishedSelf,
		GuaJiPunishedTarget,
		GuaJiPunished,
		LobbyShutDown = 600,
		AuthenticationFail = 10101,
		UserExist,
		UserNotExist,
		NoAwards,
		MailExist,
		NickNameExist,
		MailIsEmpty,
		PassWordIsEmpty,
		The3rdUserNotRegistered,
		NickNameIsEmpty,
		PvpResultEmpty,
		CallBackIsFail,
		CallBackIsNull,
		UserIsNotGuest,
		UniqueItemIsExists = 10201,
		HeroIsExists,
		GoodTypeIsNotExists,
		BuyPurchaseLimit,
		CostTypeIsNotExists,
		StoreGoodsIsNotExists,
		GameItemsIsNotExists,
		RunePositionError = 10301,
		RuneNotEquip,
		HeroDataUpdateError,
		FriendExist = 20101,
		FriendNotExist,
		FriendOffline,
		FriendInBlacklist,
		MyFriendCountLimit,
		TargetFriendCountLimit,
		InTargetBlacklist,
		MyBlackCountLimit,
		ApplyFriendAlready,
		HeroNotFound = 20201,
		SkinNotExists,
		SkinIsExists,
		DiamondShortage,
		HeroMainInfoNotExists,
		SkinNotBelongToHero,
		SkinInfoNotExists,
		RoomFull = 30101,
		TableFull,
		TableNotExist,
		OnlyFriendsCanJoin,
		GameEnded,
		ChipsNotEnough,
		UserNotInRoom,
		RoomPlayerEscape,
		RoomPlayerHeroCountNotEnough,
		RoomPlayerLackOfTicket,
		KickErrorOwner = 30201,
		KickErrorLevel,
		KickErrorLimit,
		KickErrorPlaying,
		LevelError,
		ItemExist = 40101,
		VerifyFail = 50101,
		CDTimeError = 60101,
		DayCountError,
		UnionFull = 60201,
		UnionReqFull,
		BuyItemNotFound = 50201,
		BuyItemChipNotEnough,
		BuyItemUserNotExist,
		OperationDenied = -3,
		OperationInvalid,
		InternalServerError,
		InvalidAuthentication = 32767,
		GameIdAlreadyExists = 32766,
		GameFull = 32765,
		GameClosed = 32764,
		AlreadyMatched = 32763,
		ServerFull = 32762,
		UserBlocked = 32761,
		NoMatchFound = 32760,
		RedirectRepeat = 32759,
		GameIdNotExists = 32758,
		ChipError = 70001,
		RewardVideoError,
		MagicBottleItemError,
		SigndayError
	}
}
