using System;

public enum ClientV2V
{
	ClientV2V_begin = 26001,
	PvpMapChosen,
	GetDiamonds,
	GetCaps,
	GetHero,
	GetHeroSkin,
	GetHeadPortrait,
	GetPortraitFrame,
	GetRune,
	GetCoin,
	GetBottle,
	GetExchange,
	GetExp,
	GetGameItem,
	GetCoupon,
	GetGameBuff,
	GetSpeaker,
	RecommendEquipToggle,
	DetailedShopToggle,
	SetSkillPanelPivot,
	BattleShop_shopOpened,
	BattleShop_shopClosed,
	BattleController_Close,
	BattleController_Open,
	Activity_setCurActivity,
	Activity_openView,
	Activity_noticeTaskStateChange,
	GameVideo_ShowLocalRecordPage,
	GameVideo_ShowCSTV,
	GameVideo_ShowDeleteVideoBtn,
	GameVideo_DeleteMe,
	GameVideo_ShowMe,
	GameVideo_SubmitLiveSetting,
	GameVideo_ReplaySpeedChange,
	ClientV2V_end = 27000
}
