using System;

namespace MobaHeros
{
	public enum AttrType
	{
		None,
		Hp,
		Mp,
		Power,
		Agile,
		Intelligence,
		Attack,
		Armor,
		DodgeProp,
		MoveSpeed,
		AttackSpeed,
		HpMax = 12,
		MpMax,
		HpRestore,
		MpRestore,
		HitProp = 18,
		AttackRange = 20,
		MagicResist = 23,
		PhysicPower,
		MagicPower,
		PhysicCritProp,
		MagicCritProp,
		PhysicCritMag,
		MagicCritMag,
		ArmorCut,
		MagicResistanceCut,
		Shield,
		WarningRange,
		PowerGroth,
		AgileGroth,
		IntelligenceGroth,
		PhysicDamageAdd = 38,
		PhysicDamagePercent,
		MagicDamageAdd,
		MagicDamagePercent,
		AttackDamageAdd,
		AttackDamagePercent,
		PhysicDamageCut,
		PhysicDamagePercentCut,
		MagicDamageCut,
		MagicDamagePercentCut,
		AttackDamageCut,
		AttackDamagePercentCut,
		MoFaHuDunCoverProportion,
		ArmorCut_Percentage = 60,
		MagicResistanceCut_Percentage,
		FogRange,
		ExtraAttack,
		GrowthHp,
		GrowthAttack,
		GrowthMagicPower,
		GrowthArmor,
		GrowthResistance,
		NormalSkillCooling,
		SummonSkillCooling,
		ItemSkillCooling,
		LifeSteal,
		DamageMultiple,
		SalaryExpAdd = 79,
		SalaryMoneyAdd,
		RealSightRange,
		End = 99
	}
}
