using System;

namespace MobaProtocol.Data
{
	public enum TaskType
	{
		TT_LOGIN = 1,
		TT_WINGAME,
		TT_COMPLETEGAME,
		TT_TEAMWIN,
		TT_TEAMCOMPLETE,
		TT_MAGICBOTTLE,
		TT_CURRENCY,
		TT_FRIEND,
		TT_HEROS,
		TT_SKIN,
		TT_FUWEN,
		TT_HEROPROF,
		TT_RANK,
		TT_HONOR,
		TT_GAMEDATA,
		TT_KILLNPC,
		TT_SUMMONER,
		TT_SHAREGAME,
		TT_BUYMONEY,
		TT_MAKEFUWEN,
		TT_KEEPWIN,
		TT_SINGLEGAMEDATA,
		TT_HASPROPS,
		TT_HASHEAD,
		TT_RANKRESULT,
		TT_PAY,
		TT_HEADERPICTURE,
		TT_SIGNDAY,
		TT_HEROFIGHT5v5,
		TT_ACTIVYTIME,
		TT_PAIWEIRANK,
		TT_FIRSTCHARGE,
		TT_SKINFIGHT,
		TT_SKINQUALITY,
		TT_SKINFIGHT_2,
		TT_SKINFIGHT_3,
		TT_SKINFIGHT_4,
		TT_SKINFIGHT_5,
		TT_KILLHONOR
	}
}
