using System;
using System.Collections.Generic;

namespace Com.Game.Module
{
	public class UICtrlDefine
	{
		public static Dictionary<WindowID, Type> mDicCtrlType = new Dictionary<WindowID, Type>
		{
			{
				WindowID.AreaView_New,
				typeof(AreaView)
			},
			{
				WindowID.ArenaModeView,
				typeof(ArenaModeView)
			},
			{
				WindowID.AwardView,
				typeof(AwardView)
			},
			{
				WindowID.AttachedPropertyView,
				typeof(AttachedPropertyView)
			},
			{
				WindowID.AnnouncementView,
				typeof(AnnouncementView)
			},
			{
				WindowID.BgView,
				typeof(BgView)
			},
			{
				WindowID.BuffView,
				typeof(BuffView)
			},
			{
				WindowID.BlackListView,
				typeof(BlackListView)
			},
			{
				WindowID.BirthView,
				typeof(BirthView)
			},
			{
				WindowID.BattleEquipmentView,
				typeof(BattleEquipmentView)
			},
			{
				WindowID.BarrageEmitterView,
				typeof(BarrageEmitterView)
			},
			{
				WindowID.BarragePlayerView,
				typeof(BarragePlayerCtrl)
			},
			{
				WindowID.BottleBookView,
				typeof(BottleBookView)
			},
			{
				WindowID.CharacterView,
				typeof(CharacterView)
			},
			{
				WindowID.ChangeAvatarView,
				typeof(ChangeAvatarView)
			},
			{
				WindowID.DetailsInfo,
				typeof(DetailsInfo)
			},
			{
				WindowID.DailyView,
				typeof(DailyView)
			},
			{
				WindowID.DownLoadApkView,
				typeof(DownLoadApkView)
			},
			{
				WindowID.FriendView,
				typeof(FriendView)
			},
			{
				WindowID.GoldView,
				typeof(GoldView)
			},
			{
				WindowID.GetItemsView,
				typeof(GetItemsView)
			},
			{
				WindowID.GameVideoView,
				typeof(GameVideoView)
			},
			{
				WindowID.HeartView,
				typeof(HeartView)
			},
			{
				WindowID.HUDView,
				typeof(HUDView)
			},
			{
				WindowID.HUDModuleManager,
				typeof(HUDModuleManager)
			},
			{
				WindowID.HomePayView,
				typeof(HomePayView)
			},
			{
				WindowID.InvitationView,
				typeof(InvitationView)
			},
			{
				WindowID.PvpRoomView,
				typeof(PvpRoomView)
			},
			{
				WindowID.LoginView_New,
				typeof(LoginView_New)
			},
			{
				WindowID.LoadView,
				typeof(LoadView)
			},
			{
				WindowID.LoadView2,
				typeof(LoadView2)
			},
			{
				WindowID.NewbieLoadView,
				typeof(NewbieLoadView)
			},
			{
				WindowID.LevelupView,
				typeof(LevelupView)
			},
			{
				WindowID.MessageView,
				typeof(MessageView)
			},
			{
				WindowID.MailView,
				typeof(MailView)
			},
			{
				WindowID.MenuView,
				typeof(MenuView)
			},
			{
				WindowID.MenuTopBarView,
				typeof(MenuTopBarView)
			},
			{
				WindowID.MenuBottomBarView,
				typeof(MenuBottomBarView)
			},
			{
				WindowID.MiniMapView,
				typeof(MiniMapView)
			},
			{
				WindowID.MailShowPanel,
				typeof(MailShowPanel)
			},
			{
				WindowID.NewWaitingView,
				typeof(NewWaitingView)
			},
			{
				WindowID.NewPopView,
				typeof(NewPopView)
			},
			{
				WindowID.NewTipView,
				typeof(NewTipView)
			},
			{
				WindowID.NewbieView,
				typeof(NewbieView)
			},
			{
				WindowID.PurchasePopupView,
				typeof(PurchasePopupView)
			},
			{
				WindowID.PVPLoadingView,
				typeof(PVPLoadingView)
			},
			{
				WindowID.PVPV3LoadView,
				typeof(PVPV3LoadView)
			},
			{
				WindowID.PassportView,
				typeof(PassportView)
			},
			{
				WindowID.PropertyView,
				typeof(PropertyView)
			},
			{
				WindowID.SynthesisPopupView,
				typeof(SynthesisPopupView)
			},
			{
				WindowID.HomeChatview,
				typeof(HomeChatview)
			},
			{
				WindowID.TrumpetView,
				typeof(TrumpetView)
			},
			{
				WindowID.RedPacketView,
				typeof(RedPacketView)
			},
			{
				WindowID.RunesOverView,
				typeof(RunesOverView)
			},
			{
				WindowID.PvpSelectHeroView,
				typeof(PvpSelectHeroView)
			},
			{
				WindowID.PvpWaitView,
				typeof(PvpWaitView)
			},
			{
				WindowID.PvpChoiceSkillView,
				typeof(PvpChoiceSkillView)
			},
			{
				WindowID.PvpEntranceView,
				typeof(UIPvpEntranceCtrl)
			},
			{
				WindowID.ReturnView,
				typeof(ReturnView)
			},
			{
				WindowID.RegularView,
				typeof(RegularView)
			},
			{
				WindowID.ReplayControllerView,
				typeof(ReplayControllerView)
			},
			{
				WindowID.RankView,
				typeof(RankView)
			},
			{
				WindowID.StartView_New,
				typeof(StartView_New)
			},
			{
				WindowID.SkillView,
				typeof(SkillView)
			},
			{
				WindowID.SacrificialView,
				typeof(SacrificialView)
			},
			{
				WindowID.SummonerView,
				typeof(SummonerView)
			},
			{
				WindowID.StatisticView,
				typeof(StatisticView)
			},
			{
				WindowID.ShopViewNew,
				typeof(ShopView)
			},
			{
				WindowID.SignView,
				typeof(SignView)
			},
			{
				WindowID.SystemSettingView,
				typeof(SystemSettingView)
			},
			{
				WindowID.SelectView,
				typeof(SelectView)
			},
			{
				WindowID.SummonerSkillView,
				typeof(SummonerSkillView)
			},
			{
				WindowID.ShowEquipmentPanelView,
				typeof(ShowEquipmentPanelView)
			},
			{
				WindowID.SummonerRegisterView,
				typeof(SummonerRegisterView)
			},
			{
				WindowID.SettlementMaskView,
				typeof(SettlementMaskView)
			},
			{
				WindowID.TipView,
				typeof(TipView)
			},
			{
				WindowID.TaskView,
				typeof(TaskView)
			},
			{
				WindowID.TeamSignalView,
				typeof(TeamSignalView)
			},
			{
				WindowID.TemplateView,
				typeof(TemplateView)
			},
			{
				WindowID.UnlockView,
				typeof(UnlockView)
			},
			{
				WindowID.VictoryView,
				typeof(BattleSettlementView)
			},
			{
				WindowID.MainBg,
				typeof(MainBgCtrl)
			},
			{
				WindowID.ObserveView,
				typeof(ObserveView)
			},
			{
				WindowID.BottleSystemView,
				typeof(BottleSystemView)
			},
			{
				WindowID.ActivityView,
				typeof(ActivityView)
			},
			{
				WindowID.SurrenderView,
				typeof(SurrenderView)
			},
			{
				WindowID.CaptureScreenView,
				typeof(CaptureScreenView)
			},
			{
				WindowID.SceneEditor,
				typeof(UISceneEditor)
			},
			{
				WindowID.AchievementView,
				typeof(AchievementView)
			},
			{
				WindowID.ProgressView,
				typeof(ProgressView)
			}
		};
	}
}
