using System;

namespace Com.Game.Module
{
	public enum WindowID
	{
		ENULL,
		AreaView_New,
		ArenaModeView,
		AwardView,
		AttachedPropertyView,
		AnnouncementView,
		AchievementView,
		WebView,
		BgView = 10,
		BagView,
		BuffView,
		BattleHistoryView = 14,
		BlackListView,
		BirthView,
		BattleDataView,
		BattleEquipmentView,
		BarrageEmitterView,
		BarragePlayerView,
		BottleSystemView,
		ActivityView,
		BottleBookView,
		CharacterView = 30,
		CardView,
		CaptureScreenView,
		ChangeAvatarView,
		DataView = 35,
		DLDView,
		DetailsInfo,
		DailyView,
		DownLoadApkView,
		EnchantingView,
		FPSView = 45,
		FightSweepView,
		FriendView,
		GoldHandView = 50,
		GetPowerView,
		GoldView,
		GetRewardView,
		GetItemsView,
		GameVideoView,
		HeartView = 60,
		HUDView,
		HUDModuleManager,
		HomePayView,
		InvitationView = 65,
		PvpRoomView = 70,
		LoginView_New = 75,
		LogoView,
		LoadView,
		LevelupView,
		LoadView2,
		NewbieLoadView,
		MessageView = 85,
		MailView,
		MenuView,
		MiniMapView,
		MedalView,
		MenuTopBarView,
		MenuBottomBarView,
		MedalEffectView,
		NewWaitingView,
		MainBg,
		MailShowPanel,
		NewPopView = 97,
		NewTipView,
		NewBattleView,
		NewSelectHeroView,
		NewbieView,
		ObserveView = 103,
		PVPV3LoadView,
		PVPLoadingView,
		PassportView,
		PropertyView,
		PvpSelectHeroView,
		PvpChoiceSkillView,
		PvpEntranceView,
		PurchasePopupView,
		PvpWaitView,
		SynthesisPopupView,
		HomeChatview,
		ReturnView,
		RegularView,
		ReplayView,
		RankView,
		RunesOverView,
		ReplayControllerView,
		RedPacketView,
		TrumpetView,
		StartView_New = 125,
		SkillView,
		SacrificialView,
		SummonerView,
		StatisticView,
		ShopViewNew,
		SummonerDisplayView,
		SoulStoneView,
		SignView,
		SystemSettingView,
		SocietyView,
		SelectView,
		SummonerSkillView,
		ShowEquipmentPanelView,
		SurrenderView,
		SceneEditor,
		SummonerRegisterView,
		SettlementMaskView,
		TipView = 145,
		TestModeView2,
		TaskView,
		TimeHoleView,
		TeamSignalView,
		TestModeView,
		TalentView,
		TimeHoleBattleView,
		TBCBattleView,
		TemplateView,
		UnlockView = 160,
		VictoryView = 165,
		XLDView = 170,
		ProgressView
	}
}
